In [1]:
#Dependencies
import pandas as pd
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from pathlib import Path
import matplotlib.pyplot as plt
from _spotsecrets import client_id, client_secret



# access data
path= 'Resources/charts.csv'

#create dataframe
spotify_main_data = pd.read_csv(path)
spotify_main_data.head()

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0

In [2]:
#get list of regions
# Get a list of all unique values in the 'region' column
region_list = spotify_main_data['region'].unique()

# Display the list of unique values
print(region_list)

['Argentina' 'Australia' 'Brazil' 'Austria' 'Belgium' 'Colombia' 'Bolivia'
 'Denmark' 'Bulgaria' 'Canada' 'Chile' 'Costa Rica' 'Czech Republic'
 'Finland' 'Dominican Republic' 'Ecuador' 'El Salvador' 'Estonia' 'France'
 'Germany' 'Global' 'Greece' 'Guatemala' 'Honduras' 'Hong Kong' 'Hungary'
 'Iceland' 'Indonesia' 'Ireland' 'Italy' 'Japan' 'Latvia' 'Lithuania'
 'Malaysia' 'Luxembourg' 'Mexico' 'Netherlands' 'New Zealand' 'Nicaragua'
 'Norway' 'Panama' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Singapore' 'Spain' 'Slovakia' 'Sweden' 'Taiwan' 'Switzerland' 'Turkey'
 'United Kingdom' 'United States' 'Uruguay' 'Thailand' 'Andorra' 'Romania'
 'Vietnam' 'Egypt' 'India' 'Israel' 'Morocco' 'Saudi Arabia'
 'South Africa' 'United Arab Emirates' 'Russia' 'Ukraine' 'South Korea']

In [3]:
#Only United States

USA_df = spotify_main_data[spotify_main_data['region'] == 'United States']


# Display the updated DataFrame
USA_df.head()

,title,rank,date,artist,url,region,chart,trend,streams
8246,Bad and Boujee (feat. Lil Uzi Vert),1,2017-01-01,Migos,https://open.spotify.com/track/4Km5HrUvYTaSUfi...,United States,top200,SAME_POSITION,1371493.0
8247,Fake Love,2,2017-01-01,Drake,https://open.spotify.com/track/343YBumqHu19cGo...,United States,top200,SAME_POSITION,1180074.0
8248,Starboy,3,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,United States,top200,SAME_POSITION,1064351.0
8249,Closer,4,2017-01-01,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,United States,top200,SAME_POSITION,1010492.0
8250,Black Beatles,5,2017-01-01,"Rae Sremmurd, Gucci Mane",https://open.spotify.com/track/6fujklziTHa8uoM...,United States,top200,SAME_POSITION,874289.0

In [4]:


# Create a directory named "Output" if it doesn't exist
Path("Output").mkdir(exist_ok=True)

# Save the DataFrame as a CSV in the "Output" directory
USA_df.to_csv("Output/Spotify_USA_only.csv", index=False)

In [5]:
USA_df.dtypes

title       object
rank         int64
date        object
artist      object
url         object
region      object
chart       object
trend       object
streams    float64
dtype: object

In [6]:
#get list of chart
# Get a list of all unique values in the 'chart' column
chart_list = USA_df['chart'].unique()

# Display the list of unique values
print(chart_list)

['top200' 'viral50']

In [7]:
# Create a new DataFrame that only contains rows where 'chart' is 'top200'
USA_top200_df = USA_df[USA_df['chart'] == 'top200']

# Display the updated DataFrame
USA_top200_df.head(100)

,title,rank,date,artist,url,region,chart,trend,streams
8246,Bad and Boujee (feat. Lil Uzi Vert),1,2017-01-01,Migos,https://open.spotify.com/track/4Km5HrUvYTaSUfi...,United States,top200,SAME_POSITION,1371493.0
8247,Fake Love,2,2017-01-01,Drake,https://open.spotify.com/track/343YBumqHu19cGo...,United States,top200,SAME_POSITION,1180074.0
8248,Starboy,3,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,United States,top200,SAME_POSITION,1064351.0
8249,Closer,4,2017-01-01,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,United States,top200,SAME_POSITION,1010492.0
8250,Black Beatles,5,2017-01-01,"Rae Sremmurd, Gucci Mane",https://open.spotify.com/track/6fujklziTHa8uoM...,United States,top200,SAME_POSITION,874289.0
...,...,...,...,...,...,...,...,...,...
8342,Don't,96,2017-01-01,Bryson Tiller,https://open.spotify.com/track/3pXF1nA74528Edd...,United States,top200,MOVE_DOWN,213378.0
8343,Water,97,2017-01-01,Ugly God,https://open.spotify.com/track/6HEIBHUirx1J0Jk...,United States,top200,MOVE_UP,210924.0
8344,Rich Girl,98,2017-01-01,Daryl Hall & John Oates,https://open.spotify.com/track/0qRR9d89hIS0MHR...,United States,top200,NEW_ENTRY,210173.0
8345,Erase Your Social,99,2017-01-01,Lil Uzi Vert,https://open.spotify.com/track/4uhvMW7ly7tJil3...,United States,top200,MOVE_DOWN,208263.0
8346,Never Be Like You,100,2017-01-01,"Flume, kai",https://open.spotify.com/track/12REd1n8PeiHHWO...,United States,top200,MOVE_DOWN,207102.0

In [8]:
#Keep only Top 10

USA_top10_df = USA_top200_df[(USA_top200_df['rank'] >= 1) & (USA_top200_df['rank'] <= 10)]


# Display the updated DataFrame
USA_top10_df.head()

,title,rank,date,artist,url,region,chart,trend,streams
8246,Bad and Boujee (feat. Lil Uzi Vert),1,2017-01-01,Migos,https://open.spotify.com/track/4Km5HrUvYTaSUfi...,United States,top200,SAME_POSITION,1371493.0
8247,Fake Love,2,2017-01-01,Drake,https://open.spotify.com/track/343YBumqHu19cGo...,United States,top200,SAME_POSITION,1180074.0
8248,Starboy,3,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,United States,top200,SAME_POSITION,1064351.0
8249,Closer,4,2017-01-01,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,United States,top200,SAME_POSITION,1010492.0
8250,Black Beatles,5,2017-01-01,"Rae Sremmurd, Gucci Mane",https://open.spotify.com/track/6fujklziTHa8uoM...,United States,top200,SAME_POSITION,874289.0

In [9]:
# Check for duplicates in the 'title' column
duplicates = USA_top10_df.duplicated(subset=['title'])

# Count the number of duplicates
num_duplicates = duplicates.sum()

# Print the number of duplicates found
print(f"Found {num_duplicates} duplicate titles.")

Found 17334 duplicate titles.

In [10]:
#Same title - keeps first date
title_by_month_df = USA_top10_df.groupby('title').first().reset_index()
title_by_month_df.head()

,title,rank,date,artist,url,region,chart,trend,streams
0,...Ready For It?,3,2017-09-03,Taylor Swift,https://open.spotify.com/track/19WjVVgXjdKXfLX...,United States,top200,NEW_ENTRY,1229149.0
1,1 0 0 . m i l ‘ (with Bas),5,2021-05-14,J. Cole,https://open.spotify.com/track/4n6NDfYake476tr...,United States,top200,NEW_ENTRY,3145378.0
2,"1 step forward, 3 steps back",6,2021-05-21,Olivia Rodrigo,https://open.spotify.com/track/4wcBRRpIfesgcyU...,United States,top200,NEW_ENTRY,2296296.0
3,1-800-273-8255,9,2017-06-01,"Logic, Alessia Cara, Khalid",https://open.spotify.com/track/5tz69p7tJuGPeMG...,United States,top200,SAME_POSITION,925667.0
4,10 Freaky Girls (with 21 Savage),7,2018-11-02,Metro Boomin,https://open.spotify.com/track/43lYaovU2FoeuBM...,United States,top200,NEW_ENTRY,1054273.0

In [11]:
# convert the date column to a datetime data type
title_by_month_df['date'] = pd.to_datetime(title_by_month_df['date'])

title_by_month_df.head(100)

,title,rank,date,artist,url,region,chart,trend,streams
0,...Ready For It?,3,2017-09-03,Taylor Swift,https://open.spotify.com/track/19WjVVgXjdKXfLX...,United States,top200,NEW_ENTRY,1229149.0
1,1 0 0 . m i l ‘ (with Bas),5,2021-05-14,J. Cole,https://open.spotify.com/track/4n6NDfYake476tr...,United States,top200,NEW_ENTRY,3145378.0
2,"1 step forward, 3 steps back",6,2021-05-21,Olivia Rodrigo,https://open.spotify.com/track/4wcBRRpIfesgcyU...,United States,top200,NEW_ENTRY,2296296.0
3,1-800-273-8255,9,2017-06-01,"Logic, Alessia Cara, Khalid",https://open.spotify.com/track/5tz69p7tJuGPeMG...,United States,top200,SAME_POSITION,925667.0
4,10 Freaky Girls (with 21 Savage),7,2018-11-02,Metro Boomin,https://open.spotify.com/track/43lYaovU2FoeuBM...,United States,top200,NEW_ENTRY,1054273.0
...,...,...,...,...,...,...,...,...,...
95,Bodak Yellow,10,2017-08-13,Cardi B,https://open.spotify.com/track/2771LMNxwf62FTA...,United States,top200,MOVE_UP,668859.0
96,Body,10,2020-11-24,Megan Thee Stallion,https://open.spotify.com/track/0A1hoCfMLkiAgvh...,United States,top200,MOVE_UP,725697.0
97,Bounce Back,10,2017-01-01,Big Sean,https://open.spotify.com/track/0SGkqnVQo9KPytS...,United States,top200,MOVE_DOWN,682688.0
98,Bout A Million (feat. 42 Dugg & 21 Savage),6,2021-07-16,Pop Smoke,https://open.spotify.com/track/4LaGu95Ui2s4vpr...,United States,top200,NEW_ENTRY,1046352.0
99,Boy With Luv (feat. Halsey),4,2019-04-12,BTS,https://open.spotify.com/track/5KawlOMHjWeUjQt...,United States,top200,NEW_ENTRY,1314671.0

In [12]:
# Check for duplicates in the 'title' column
duplicates2 = title_by_month_df.duplicated(subset=['title'])

# Count the number of duplicates
num_duplicates2 = duplicates2.sum()

# Print the number of duplicates found
print(f"Found {num_duplicates2} duplicate titles.")

title_by_month_df.count()

Found 0 duplicate titles.

title      874
rank       874
date       874
artist     874
url        874
region     874
chart      874
trend      874
streams    874
dtype: int64

In [13]:
#grab Spotify Track Id from URL and add in a new column named 'Spotify Track Id'

title_by_month_df['Spotify Track Id'] = title_by_month_df['url'].str.split('/').str[-1]
title_by_month_df.head()

,title,rank,date,artist,url,region,chart,trend,streams,Spotify Track Id
0,...Ready For It?,3,2017-09-03,Taylor Swift,https://open.spotify.com/track/19WjVVgXjdKXfLX...,United States,top200,NEW_ENTRY,1229149.0,19WjVVgXjdKXfLXoaDPwTM
1,1 0 0 . m i l ‘ (with Bas),5,2021-05-14,J. Cole,https://open.spotify.com/track/4n6NDfYake476tr...,United States,top200,NEW_ENTRY,3145378.0,4n6NDfYake476trCjJRNl0
2,"1 step forward, 3 steps back",6,2021-05-21,Olivia Rodrigo,https://open.spotify.com/track/4wcBRRpIfesgcyU...,United States,top200,NEW_ENTRY,2296296.0,4wcBRRpIfesgcyUtis7PEg
3,1-800-273-8255,9,2017-06-01,"Logic, Alessia Cara, Khalid",https://open.spotify.com/track/5tz69p7tJuGPeMG...,United States,top200,SAME_POSITION,925667.0,5tz69p7tJuGPeMGwNTxYuV
4,10 Freaky Girls (with 21 Savage),7,2018-11-02,Metro Boomin,https://open.spotify.com/track/43lYaovU2FoeuBM...,United States,top200,NEW_ENTRY,1054273.0,43lYaovU2FoeuBMNusVVVW

In [14]:
#pretty names that make sense

USA_top10_df= title_by_month_df

In [15]:
#FOR REAL DATA

# Authenticate with the Spotify API using client credentials flow
client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

# Load the Spotify Track Id column from the dataframe
track_ids = USA_top10_df['Spotify Track Id']

# Create empty lists to store the audio feature data
danceability = []
energy = []
key = []
loudness = []
mode = []
speechiness = []
acousticness = []
instrumentalness = []
liveness = []
valence = []
tempo = []
duration_ms = []

# Iterate through each track id in the column and make a request to the Spotify API for its audio features
for track_id in track_ids:
    audio_features = sp.audio_features(track_id)[0]
    danceability.append(audio_features['danceability'])
    energy.append(audio_features['energy'])
    key.append(audio_features['key'])
    loudness.append(audio_features['loudness'])
    mode.append(audio_features['mode'])
    speechiness.append(audio_features['speechiness'])
    acousticness.append(audio_features['acousticness'])
    instrumentalness.append(audio_features['instrumentalness'])
    liveness.append(audio_features['liveness'])
    valence.append(audio_features['valence'])
    tempo.append(audio_features['tempo'])
    duration_ms.append(audio_features['duration_ms'])

# Add the audio feature data to the dataframe as new columns
USA_top10_df['danceability'] = danceability
USA_top10_df['energy'] = energy
USA_top10_df['key'] = key
USA_top10_df['loudness'] = loudness
USA_top10_df['mode'] = mode
USA_top10_df['speechiness'] = speechiness
USA_top10_df['acousticness'] = acousticness
USA_top10_df['instrumentalness'] = instrumentalness
USA_top10_df['liveness'] = liveness
USA_top10_df['valence'] = valence
USA_top10_df['tempo'] = tempo
USA_top10_df['duration_ms'] = duration_ms

# Print the updated dataframe
USA_top10_df.head()

,title,rank,date,artist,url,region,chart,trend,streams,Spotify Track Id,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,...Ready For It?,3,2017-09-03,Taylor Swift,https://open.spotify.com/track/19WjVVgXjdKXfLX...,United States,top200,NEW_ENTRY,1229149.0,19WjVVgXjdKXfLXoaDPwTM,...,2,-6.500,1,0.1420,0.0573,0.0,0.159,0.4120,160.049,208198
1,1 0 0 . m i l ‘ (with Bas),5,2021-05-14,J. Cole,https://open.spotify.com/track/4n6NDfYake476tr...,United States,top200,NEW_ENTRY,3145378.0,4n6NDfYake476trCjJRNl0,...,2,-5.667,0,0.0822,0.3340,0.0,0.312,0.2270,125.092,163302
2,"1 step forward, 3 steps back",6,2021-05-21,Olivia Rodrigo,https://open.spotify.com/track/4wcBRRpIfesgcyU...,United States,top200,NEW_ENTRY,2296296.0,4wcBRRpIfesgcyUtis7PEg,...,2,-12.627,1,0.1020,0.9410,0.0,0.126,0.4190,168.884,163587
3,1-800-273-8255,9,2017-06-01,"Logic, Alessia Cara, Khalid",https://open.spotify.com/track/5tz69p7tJuGPeMG...,United States,top200,SAME_POSITION,925667.0,5tz69p7tJuGPeMGwNTxYuV,...,5,-7.788,0,0.0479,0.5690,0.0,0.190,0.3570,100.023,250173
4,10 Freaky Girls (with 21 Savage),7,2018-11-02,Metro Boomin,https://open.spotify.com/track/43lYaovU2FoeuBM...,United States,top200,NEW_ENTRY,1054273.0,43lYaovU2FoeuBMNusVVVW,...,6,-9.931,0,0.3100,0.5880,0.0,0.102,0.0727,88.031,208293

In [ ]:
# Create a directory named "Output" if it doesn't exist
Path("Output").mkdir(exist_ok=True)

# Save the DataFrame as a CSV in the "Output" directory
USA_top10_df.to_csv("Output/Spotify_USA_Top10.csv", index=False)

In [ ]:
#get list of keys
# Get a list of all unique values in the 'key' column
key_list = USA_top10_df['key'].unique()

# Display the list of unique values
print(key_list)

In [ ]:
#Convert key to Alpha
key_letters = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
USA_top10_df['key'] = USA_top10_df['key'].astype(int).apply(lambda x: key_letters[x % 12] if x != -1 else 'Unknown Key')

USA_top10_df.head(100)

In [ ]:
#get list of keys in Alpha
# Get a list of all unique values in the 'key' column
key_list_alpha = USA_top10_df['key'].unique()

# Display the list of unique values
print(key_list_alpha)

In [ ]:
#Convert mode to Alpha
mode_alpha = ['Maj', 'Min']
USA_top10_df['mode'] = USA_top10_df['mode'].astype(int).apply(lambda x: mode_alpha[x % 12] if x != -1 else 'Unknown Mode')

USA_top10_df.head(100)

In [ ]:
#get list of modes in Alpha
# Get a list of all unique values in the 'key' column
mode_list_alpha = USA_top10_df['mode'].unique()

# Display the list of unique values
print(mode_list_alpha)

In [ ]:
#Round Up Tempo
import math

# Round up the 'tempo' column to the nearest whole number
USA_top10_df['tempo'] = USA_top10_df['tempo'].apply(lambda x: math.ceil(x))
USA_top10_df.head()

In [ ]:
#Convert Duration
# convert milliseconds to minutes
USA_top10_df['duration_mins'] = USA_top10_df['duration_ms'] / 60000
USA_top10_df['duration_mins']=USA_top10_df['duration_mins'].round(2)

# drop old column
top5=USA_top10_df.drop('duration_ms',axis=1)
top5.head()

In [ ]:
#Define Valence in Alpha
def valence_category(valence):
    if valence >= 0.8:
        return "Extremely Positive"
    elif valence >= 0.6:
        return "Positive"
    elif valence >= 0.4:
        return "Neutral"
    elif valence >= 0.2:
        return "Negative"
    else:
        return "Extremely Negative"

USA_top10_df['valence_category'] = USA_top10_df['valence'].apply(valence_category)
USA_top10_df.head(100)

In [ ]:
#Define Danceability in Alpha
def danceability_category(danceability):
    if danceability >= 0.8:
        return "Most Danceable"
    elif danceability >= 0.6:
        return "More Danceable"
    elif danceability >= 0.4:
        return "Danceable"
    elif danceability >= 0.2:
        return "Less Danceable"
    else:
        return "Least Danceable"

USA_top10_df['danceabity_category'] = USA_top10_df['danceability'].apply(danceability_category)
USA_top10_df.head(100)

In [ ]:
#Define Energy in Alpha
def energy_category(energy):
    if energy >= 0.8:
        return "Extremely Intense"
    elif energy >= 0.6:
        return "Intense"
    elif energy >= 0.4:
        return "Neutral"
    elif energy >= 0.2:
        return "Calm"
    else:
        return "Extremely Calm"

USA_top10_df['energy_category'] = USA_top10_df['energy'].apply(energy_category)
USA_top10_df.head(100)

In [ ]:
# Extract the year and month into separate columns
USA_top10_df['year'] = USA_top10_df['date'].dt.year
USA_top10_df['month'] = USA_top10_df['date'].dt.month
USA_top10_df['month_year'] = USA_top10_df['date'].dt.to_period('M')  # Format: YYYY-MM

# Drop the original date column if desired
USA_top10_df.drop(columns=['date'], inplace=True)

USA_top10_df.head()

In [ ]:
print(top5.columns)

In [ ]:
#Sort Columns
# Define the desired column order
column_order = ['title', 'artist', 'year', 'month', 'tempo', 'duration_mins', 'valence_category',
                'danceabity_category', 'energy_category', 'key', 'mode', 'rank', 'region', 'chart',
                'trend', 'streams', 'danceability', 'energy', 'loudness', 'speechiness', 
                'acousticness', 'instrumentalness', 'liveness', 'valence', 'url', 'Spotify Track Id']

# Reindex the DataFrame using the desired column order
top5 = top5.reindex(columns=column_order)

# Display the resulting DataFrame
top5.head(100)

In [ ]:
# Create a scatter plot of danceability vs. streams
plt.scatter(top5['streams'], top5['danceability'])
plt.xlim(0, 4*1e6)
# Add axis labels and a title
plt.xlabel('Streams')
plt.ylabel('Danceability')
plt.title('Relationship Between Streams and Danceability')

# Show the plot
plt.show()

#ADD Corellation stat stuff
#ADD Histogram

In [ ]:
# Create a scatter plot of danceability vs. streams
plt.scatter(top5['streams'], top5['energy'])
plt.xlim(0, 4*1e6)
# Add axis labels and a title
plt.xlabel('Streams')
plt.ylabel('Energy')
plt.title('Relationship Between Streams and Energy')

# Show the plot
plt.show()

In [ ]:
# Create a scatter plot of danceability vs. streams
plt.scatter(top5['energy'], top5['danceability'])

# Add axis labels and a title
plt.xlabel('Energy')
plt.ylabel('Danceability')
plt.title('Relationship Between Energy and Danceability')

# Show the plot
plt.show()

In [ ]:
import seaborn as sns

sns.set_style('darkgrid')

sns.scatterplot(data=top5, x='energy', y='danceability', hue='valence_category', style='energy_category', size='danceability')

plt.title('Top 5 Songs: Energy vs Danceability')
plt.xlabel('Energy')
plt.ylabel('Danceability')
plt.show()

In [ ]:
# Group the data by year and mode, and calculate the count for each group
df_monthly5 = top5.groupby(['year', 'mode']).size().reset_index(name='count')

# Pivot the data to create a separate column for each mode
df_pivot = df_monthly5.pivot(index='year', columns='mode', values='count')

# Plot the mode popularity over time using a bar chart
ax = df_pivot.plot(kind='bar', stacked=True, figsize=(10, 6))
ax.set_xlabel('Year')
ax.set_ylabel('Count')
ax.set_title('Mode Popularity Over Time')
plt.show()

#ADD % within Bars

In [ ]:
# Group the data by year and mode, and calculate the count for each group
df_monthly6 = top5.groupby(['year', 'valence_category']).size().reset_index(name='count')

# Pivot the data to create a separate column for each mode
df_pivot = df_monthly6.pivot(index='year', columns='valence_category', values='count')

# Plot the mode popularity over time using a bar chart
ax = df_pivot.plot(kind='bar', stacked=True, figsize=(10, 6))
ax.set_xlabel('Year')
ax.set_ylabel('Count')
ax.set_title('Valence Popularity Over Time')
plt.show()

In [ ]:
# Group the data by year and mode, and calculate the count for each group
df_monthly6 = top5.groupby(['year', 'energy_category']).size().reset_index(name='count')

# Pivot the data to create a separate column for each mode
df_pivot = df_monthly6.pivot(index='year', columns='energy_category', values='count')

# Plot the mode popularity over time using a bar chart
ax = df_pivot.plot(kind='bar', stacked=True, figsize=(10, 6))
ax.set_xlabel('Year')
ax.set_ylabel('Count')
ax.set_title('Energy Popularity Over Time')
plt.show()